name: Verilog AGC Simulation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Install ilcarus verilog
        run: sudo apt install iverilog -y
      - name: Setup yaYUL
        run: ./scripts/setup_yaYUL.sh
      - name: Downloading Luminary099 source and compiling
        run: ./scripts/download_rom.sh Luminary099
      - name: Simulate
        run: make simulate
